In [1]:
import numpy as np

def diagonalize(A):


    # Compute the eigenvalues and eigenvectors of A
    eigvals, eigvecs = np.linalg.eig(A)

    # Construct the diagonal matrix of eigenvalues
    Lambda = np.diag(eigvals)

    # Construct the matrix of eigenvectors
    V = eigvecs

    # Return the diagonal matrix and matrix of eigenvectors
    return Lambda, V

# Example usage
A = np.array([[5, 4, 2, 1], [0, 1, -1, -1], [-1, -1, 3, 0], [1, 1, -1, 2]])
Lambda, V = diagonalize(A)
print("Lambda:", Lambda)
print("V:", V)
print(np.linalg.inv(V)@A@V)
print(A@V)
print(V@Lambda)

Lambda: [[4. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 2.]]
V: [[-5.77350269e-01  5.77350269e-01 -7.07106781e-01 -5.77350269e-01]
 [ 0.00000000e+00  0.00000000e+00  7.07106781e-01  5.77350269e-01]
 [ 5.77350269e-01 -5.77350269e-01  1.55241466e-16  4.98571317e-16]
 [-5.77350269e-01  5.77350269e-01  4.18918462e-16 -5.77350269e-01]]
[[ 3.61658075e+00  3.83419246e-01 -1.11863265e+00 -1.97600420e+00]
 [-1.38341925e+00  4.88341925e+00 -1.11863265e+00 -1.97600420e+00]
 [-1.11022302e-16  1.11022302e-16  1.00000000e+00  1.66533454e-15]
 [ 2.22044605e-16 -2.22044605e-16 -1.04689286e-15  2.00000000e+00]]
[[-2.30940108e+00  2.30940108e+00 -7.07106781e-01 -1.15470054e+00]
 [ 0.00000000e+00  0.00000000e+00  7.07106781e-01  1.15470054e+00]
 [ 2.30940108e+00 -2.30940108e+00  4.65724398e-16  1.49571395e-15]
 [-2.30940108e+00  2.30940108e+00  6.82595458e-16 -1.15470054e+00]]
[[-2.30940108e+00  2.30940108e+00 -7.07106781e-01 -1.15470054e+00]
 [ 0.00000000e+00  0.00000000e+00  7.07106781e-01  1.1